from _datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QCursor

from db import registrar_cliente
from style import *
from typo import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 534)
        MainWindow.setStyleSheet(window)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setStyleSheet(lbl_title_green)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_3.addWidget(self.lbl_title)
        self.groupBox_Full = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Full.setStyleSheet(group_default)
        self.groupBox_Full.setTitle("")
        self.groupBox_Full.setObjectName("groupBox_Full")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_Full)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_Full)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet(lbl_small_grey)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.inp_nome = QtWidgets.QLineEdit(self.groupBox)
        self.inp_nome.setStyleSheet(inp_default)
        self.inp_nome.setObjectName("inp_nome")
        self.verticalLayout.addWidget(self.inp_nome)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet(lbl_small_grey)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.inp_email = QtWidgets.QLineEdit(self.groupBox)
        self.inp_email.setStyleSheet(inp_default)
        self.inp_email.setObjectName("inp_email")
        self.verticalLayout.addWidget(self.inp_email)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet(lbl_small_grey)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.inp_senha = QtWidgets.QLineEdit(self.groupBox)
        self.inp_senha.setStyleSheet(inp_default)
        self.inp_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inp_senha.setPlaceholderText("")
        self.inp_senha.setObjectName("inp_senha")
        self.verticalLayout.addWidget(self.inp_senha)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet(lbl_small_grey)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.inp_senha_novamente = QtWidgets.QLineEdit(self.groupBox)
        self.inp_senha_novamente.setStyleSheet(inp_default)
        self.inp_senha_novamente.setText("")
        self.inp_senha_novamente.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inp_senha_novamente.setObjectName("inp_senha_novamente")
        self.verticalLayout.addWidget(self.inp_senha_novamente)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_Full)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setStyleSheet(lbl_small_grey)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.inp_agencia = QtWidgets.QLineEdit(self.groupBox_4)
        self.inp_agencia.setStyleSheet(inp_default)
        self.inp_agencia.setObjectName("inp_agencia")
        self.verticalLayout_4.addWidget(self.inp_agencia)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setStyleSheet(lbl_small_grey)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.inp_numero_conta = QtWidgets.QLineEdit(self.groupBox_4)
        self.inp_numero_conta.setStyleSheet(inp_default)
        self.inp_numero_conta.setObjectName("inp_numero_conta")
        self.verticalLayout_4.addWidget(self.inp_numero_conta)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setStyleSheet(lbl_small_grey)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.cmb_tipo = QtWidgets.QComboBox(self.groupBox_4)
        self.cmb_tipo.setStyleSheet(cmb_default)
        self.cmb_tipo.setObjectName("cmb_tipo")
        self.cmb_tipo.addItem("")
        self.cmb_tipo.addItem("")
        self.cmb_tipo.addItem("")
        self.cmb_tipo.addItem("")
        self.verticalLayout_4.addWidget(self.cmb_tipo)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setStyleSheet(lbl_small_grey)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.inp_saldo = QtWidgets.QLineEdit(self.groupBox_4)
        self.inp_saldo.setStyleSheet(inp_default)
        self.inp_saldo.setInputMask("")
        self.inp_saldo.setObjectName("inp_saldo")
        self.verticalLayout_4.addWidget(self.inp_saldo)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setStyleSheet(lbl_small_grey)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.lbl_data_registro = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_data_registro.setStyleSheet(lbl_data_default)
        self.lbl_data_registro.setObjectName("lbl_data_registro")
        self.verticalLayout_4.addWidget(self.lbl_data_registro)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_Full)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet(lbl_small_grey)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setStyleSheet(color_grey)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rad_masculino = QtWidgets.QRadioButton(self.groupBox_3)
        self.rad_masculino.setChecked(True)
        self.rad_masculino.setObjectName("rad_masculino")
        self.horizontalLayout_2.addWidget(self.rad_masculino)
        self.rad_feminino = QtWidgets.QRadioButton(self.groupBox_3)
        self.rad_feminino.setObjectName("rad_feminino")
        self.horizontalLayout_2.addWidget(self.rad_feminino)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet(color_grey)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.inp_data_nascimento = QtWidgets.QDateEdit(self.groupBox_2)
        self.inp_data_nascimento.setStyleSheet(inp_data)
        self.inp_data_nascimento.setObjectName("inp_data_nascimento")
        self.verticalLayout_2.addWidget(self.inp_data_nascimento)
        self.btn_registro = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_registro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_registro.setStyleSheet(btn_green)
        self.btn_registro.setObjectName("btn_registro")
        self.verticalLayout_2.addWidget(self.btn_registro)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.groupBox_Full)
        self.lbl_mensagem = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mensagem.setStyleSheet(lbl_mensagem_default)
        self.lbl_mensagem.setText("")
        self.lbl_mensagem.setObjectName("lbl_mensagem")
        self.verticalLayout_3.addWidget(self.lbl_mensagem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Arquivo = QtWidgets.QMenu(self.menubar)
        self.menu_Arquivo.setObjectName("menu_Arquivo")
        self.menuA_juda = QtWidgets.QMenu(self.menubar)
        self.menuA_juda.setObjectName("menuA_juda")
        self.menu_Lista_de_Clientes = QtWidgets.QMenu(self.menubar)
        self.menu_Lista_de_Clientes.setObjectName("menu_Lista_de_Clientes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Registro_Funcionario = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/1388560951582004484-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Registro_Funcionario.setIcon(icon)
        self.action_Registro_Funcionario.setObjectName("action_Registro_Funcionario")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/12355707351582004488-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionContato = QtWidgets.QAction(MainWindow)
        self.actionContato.setObjectName("actionContato")
        self.action_Visualizar = QtWidgets.QAction(MainWindow)
        self.action_Visualizar.setObjectName("action_Visualizar")
        self.action_Informa_es = QtWidgets.QAction(MainWindow)
        self.action_Informa_es.setObjectName("action_Informa_es")
        self.menu_Arquivo.addAction(self.action_Registro_Funcionario)
        self.menu_Arquivo.addAction(self.action_Exit)
        self.menuA_juda.addAction(self.actionSobre)
        self.menuA_juda.addAction(self.actionContato)
        self.menu_Lista_de_Clientes.addAction(self.action_Visualizar)
        self.menu_Lista_de_Clientes.addAction(self.action_Informa_es)
        self.menubar.addAction(self.menu_Arquivo.menuAction())
        self.menubar.addAction(self.menu_Lista_de_Clientes.menuAction())
        self.menubar.addAction(self.menuA_juda.menuAction())
        self.label.setBuddy(self.inp_nome)
        self.label_2.setBuddy(self.inp_email)
        self.label_3.setBuddy(self.inp_senha)
        self.label_5.setBuddy(self.inp_senha_novamente)
        self.label_8.setBuddy(self.inp_nome)
        self.label_7.setBuddy(self.inp_numero_conta)
        self.label_10.setBuddy(self.inp_saldo)
        self.label_6.setBuddy(self.rad_masculino)
        self.label_4.setBuddy(self.inp_data_nascimento)

        '''str'''
        self.action_Exit.triggered.connect(lambda: MainWindow.close())
        self.btn_registro.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_registro.clicked.connect(self.registrar)
        self.data_agora = str(datetime.now())
        self.btn_registro.setAutoDefault(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inp_nome, self.inp_email)
        MainWindow.setTabOrder(self.inp_email, self.inp_senha)
        MainWindow.setTabOrder(self.inp_senha, self.inp_senha_novamente)
        MainWindow.setTabOrder(self.inp_senha_novamente, self.inp_agencia)
        MainWindow.setTabOrder(self.inp_agencia, self.inp_numero_conta)
        MainWindow.setTabOrder(self.inp_numero_conta, self.cmb_tipo)
        MainWindow.setTabOrder(self.cmb_tipo, self.inp_saldo)
        MainWindow.setTabOrder(self.inp_saldo, self.rad_masculino)
        MainWindow.setTabOrder(self.rad_masculino, self.rad_feminino)
        MainWindow.setTabOrder(self.rad_feminino, self.inp_data_nascimento)
        MainWindow.setTabOrder(self.inp_data_nascimento, self.btn_registro)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "Registro de Cliente"))
        self.groupBox.setTitle(_translate("MainWindow", "Dados Pessoais"))
        self.label.setText(_translate("MainWindow", "Nome Completo"))
        self.inp_nome.setPlaceholderText(_translate("MainWindow", "Nome Completo"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.inp_email.setPlaceholderText(_translate("MainWindow", "email@email.com"))
        self.label_3.setText(_translate("MainWindow", "Senha"))
        self.label_5.setText(_translate("MainWindow", "Senha Novamente"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dados da Conta"))
        self.label_8.setText(_translate("MainWindow", "Agência"))
        self.inp_agencia.setPlaceholderText(_translate("MainWindow", "AG-0000"))
        self.inp_agencia.setText(_translate("MainWindow", "AG-"))
        self.label_7.setText(_translate("MainWindow", "Número da Conta"))
        self.inp_numero_conta.setPlaceholderText(_translate("MainWindow", "00000"))
        self.label_9.setText(_translate("MainWindow", "Tipo da Conta"))
        self.cmb_tipo.setItemText(0, _translate("MainWindow", "Corrente"))
        self.cmb_tipo.setItemText(1, _translate("MainWindow", "Poupança"))
        self.cmb_tipo.setItemText(2, _translate("MainWindow", "Salário"))
        self.cmb_tipo.setItemText(3, _translate("MainWindow", "Simples"))
        self.label_10.setText(_translate("MainWindow", "Saldo"))
        self.inp_saldo.setPlaceholderText(_translate("MainWindow", "R$ 00.00"))
        self.label_11.setText(_translate("MainWindow", "Data de Registro"))
        self.lbl_data_registro.setText(_translate("MainWindow", self.data_agora))
        self.groupBox_2.setTitle(_translate("MainWindow", "Informações adicionais"))
        self.label_6.setText(_translate("MainWindow", "Gênero"))
        self.rad_masculino.setText(_translate("MainWindow", "Masculino"))
        self.rad_feminino.setText(_translate("MainWindow", "Feminino"))
        self.label_4.setText(_translate("MainWindow", "Data de Nascimento"))
        self.btn_registro.setText(_translate("MainWindow", "Registrar Cliente"))
        self.menu_Arquivo.setTitle(_translate("MainWindow", "&Arquivo"))
        self.menuA_juda.setTitle(_translate("MainWindow", "A&juda"))
        self.menu_Lista_de_Clientes.setTitle(_translate("MainWindow", "&Clientes"))
        self.action_Registro_Funcionario.setText(_translate("MainWindow", "&Registro de Funcionários"))
        self.action_Registro_Funcionario.setStatusTip(_translate("MainWindow", "Voltar para tela de Login"))
        self.action_Registro_Funcionario.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setStatusTip(_translate("MainWindow", "Fechar o aplicativo"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionContato.setText(_translate("MainWindow", "Contato"))
        self.action_Visualizar.setText(_translate("MainWindow", "&Visualizar"))
        self.action_Visualizar.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_Informa_es.setText(_translate("MainWindow", "&Informações"))

    '''def'''

    def registrar(self):
        self.lbl_mensagem.setText("")
        self.lbl_mensagem.setStyleSheet(lbl_mensagem_default)

        nome = self.inp_nome.text().strip()
        email = self.inp_email.text().strip()
        senha = self.inp_senha.text()
        genero = 'masculino' if self.rad_masculino.isChecked() else 'feminino'
        data_nascimento = self.inp_data_nascimento.text()
        numero_conta = self.inp_numero_conta.text()
        agencia = self.inp_agencia.text().strip()
        tipo = self.cmb_tipo.currentText()
        saldo = self.inp_saldo.text()

        try:
            registrar_cliente(nome=nome, email=email, senha=senha, genero=genero,
                              data_nascimento=data_nascimento,
                              numero_da_conta=numero_conta, agencia=agencia,
                              tipo_da_conta=tipo, saldo=saldo)
            self.lbl_mensagem.setText(suc_registro_cliente)
            self.lbl_mensagem.setStyleSheet(lbl_mensagem_success)
        except:
            self.lbl_mensagem.setText(err_registro_generico)
            self.lbl_mensagem.setStyleSheet(lbl_mensagem_error)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
