from PyQt5 import QtCore, QtGui, QtWidgets
from ui.styles import *
from ui import Transferir, Depositar, Sacar
from db import account_client


class Ui_MainWindow(object):
    def __init__(self, usuario):
        self.usuario = usuario

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 444)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setStyleSheet(lbl_simple)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.inp_agencia = QtWidgets.QLineEdit(self.groupBox_3)
        self.inp_agencia.setStyleSheet(inp_disabled)
        self.inp_agencia.setReadOnly(True)
        self.inp_agencia.setObjectName("inp_agencia")
        self.inp_agencia.setText('AG-9999')
        self.verticalLayout_2.addWidget(self.inp_agencia)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setStyleSheet(lbl_simple)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.inp_numero_conta = QtWidgets.QLineEdit(self.groupBox_3)
        self.inp_numero_conta.setStyleSheet(inp_disabled)
        self.inp_numero_conta.setReadOnly(True)
        self.inp_numero_conta.setObjectName("inp_numero_conta")
        self.inp_numero_conta.setText(self.usuario['usuario'][2])
        self.verticalLayout_2.addWidget(self.inp_numero_conta)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setStyleSheet(lbl_simple)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.inp_tipo_conta = QtWidgets.QLineEdit(self.groupBox_3)
        self.inp_tipo_conta.setStyleSheet(inp_disabled)
        self.inp_tipo_conta.setReadOnly(True)
        self.inp_tipo_conta.setObjectName("inp_tipo_conta")
        self.inp_tipo_conta.setText(self.usuario['usuario'][3])
        self.verticalLayout_2.addWidget(self.inp_tipo_conta)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_nome_usuario = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nome_usuario.setFont(font)
        self.lbl_nome_usuario.setObjectName("lbl_nome_usuario")
        self.verticalLayout_3.addWidget(self.lbl_nome_usuario)
        ''''''
        self.lbl_email = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_email.setObjectName("lbl_email")
        self.verticalLayout_3.addWidget(self.lbl_email)
        self.lbl_email.setText(self.usuario['usuario'][1])
        ''''''
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.groupBox_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/11792205231582004499-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_saldo = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_saldo.setFont(font)
        self.lbl_saldo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_saldo.setObjectName("lbl_saldo")
        self.verticalLayout_6.addWidget(self.lbl_saldo)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/19543194281582004490-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet(lbl_title_2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 261, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/9104314201582004494-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.lbl_mensagem = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mensagem.setStyleSheet(lbl_reset)
        self.lbl_mensagem.setObjectName("lbl_mensagem")
        self.verticalLayout.addWidget(self.lbl_mensagem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Arquivo = QtWidgets.QMenu(self.menubar)
        self.menu_Arquivo.setObjectName("menu_Arquivo")
        self.menu_Opera_es = QtWidgets.QMenu(self.menubar)
        self.menu_Opera_es.setObjectName("menu_Opera_es")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Depositar = QtWidgets.QAction(MainWindow)
        self.action_Depositar.setObjectName("action_Depositar")
        self.action_Sacar = QtWidgets.QAction(MainWindow)
        self.action_Sacar.setObjectName("action_Sacar")
        self.action_Transferir = QtWidgets.QAction(MainWindow)
        self.action_Transferir.setObjectName("action_Transferir")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.menu_Arquivo.addAction(self.action_Exit)
        self.menu_Opera_es.addAction(self.action_Depositar)
        self.menu_Opera_es.addAction(self.action_Sacar)
        self.menu_Opera_es.addAction(self.action_Transferir)
        self.menuSobre.addAction(self.actionSobre)
        self.menubar.addAction(self.menu_Arquivo.menuAction())
        self.menubar.addAction(self.menu_Opera_es.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        '''edited'''
        self.action_Exit.triggered.connect(lambda : MainWindow.close())
        self.action_Depositar.triggered.connect(self.deposit)
        self.action_Sacar.triggered.connect(self.withdraw)
        self.action_Transferir.triggered.connect(self.transfer)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bankii - Minha Conta"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Informações da Conta"))
        self.label_5.setText(_translate("MainWindow", "Agência"))
        self.label_6.setText(_translate("MainWindow", "Número da Conta"))
        self.label_7.setText(_translate("MainWindow", "Tipo"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Informações da Usuário"))
        self.lbl_nome_usuario.setText(_translate("MainWindow", self.usuario['usuario'][0]))
        # adicionar email
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Início"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Saldo atual"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_saldo.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sa&ldo"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Extrato dos últimos dias"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Extrato"))
        self.lbl_mensagem.setText(_translate("MainWindow", ""))
        self.menu_Arquivo.setTitle(_translate("MainWindow", "&Arquivo"))
        self.menu_Opera_es.setTitle(_translate("MainWindow", "&Operações"))
        self.menuSobre.setTitle(_translate("MainWindow", "Ajuda"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_Depositar.setText(_translate("MainWindow", "&Depositar"))
        self.action_Depositar.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_Sacar.setText(_translate("MainWindow", "&Sacar"))
        self.action_Sacar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Transferir.setText(_translate("MainWindow", "&Transferir"))
        self.action_Transferir.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))

    def saldo(self):
        return account_client('account', account_id=self.usuario['usuario'][2])

    '''def'''
    def deposit(self):
        self.data = self.saldo()

        self.window = QtWidgets.QMainWindow()
        self.ui = Depositar.Ui_MainWindow(self.data)
        self.ui.setupUi(self.window)
        self.window.show()

    def withdraw(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Sacar.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def transfer(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Transferir.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
